version: '3'
services:

##################################################################
#  HORNET - Stardust                                             #
##################################################################

  hornet:
    container_name: hornet
    image: iotaledger/hornet:2.0
    networks:
      default:
        ipv4_address: 172.18.211.11
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    stop_grace_period: 5m
    depends_on:
      traefik:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hornet.service=hornet"
      - "traefik.http.routers.hornet.rule=Host(`localhost`)"
      - "traefik.http.routers.hornet.entrypoints=web"
      - "traefik.http.services.hornet.loadbalancer.server.port=14265"
      - "traefik.http.routers.hornet.middlewares=redirect-dashboard"
      - "traefik.http.middlewares.redirect-dashboard.redirectregex.regex=^(https?://[^/]+)/?$$"
      - "traefik.http.middlewares.redirect-dashboard.redirectregex.replacement=$$1/dashboard/"
      - "traefik.http.middlewares.redirect-dashboard.redirectregex.permanent=true"
    cap_drop:
      - ALL
    volumes:
      - ./config_sandbox.json:/app/config.json:ro
      - ./data/sandboxdb/hornet:/app/data/sandboxdb
      - ./data/snapshots/hornet:/app/data/snapshots
    command:
      - "-c"
      - "config.json"
      - "--db.path=data/sandboxdb"
      - "--p2p.db.path=data/sandboxdb"
      - "--p2p.bindMultiAddresses=/ip4/0.0.0.0/tcp/15600,/ip6/::/tcp/15600"
      - "--p2p.identityPrivateKey=1f46fad4f538a031d4f87f490f6bca4319dfd0307636a5759a22b5e8874bd608f9156ba976a12918c16a481c38c88a7b5351b769adc30390e93b6c0a63b09b79"
      - "--p2p.peers=/ip4/172.18.211.12/tcp/15600/p2p/12D3KooWCKwcTWevoRKa2kEBputeGASvEBuDfRDSbe8t1DWugUmL"
      - "--p2p.peerAliases=hornet-1"
      - "--snapshots.fullPath=data/snapshots/full_snapshot.bin"
      - "--snapshots.deltaPath=data/snapshots/delta_snapshot.bin"
      - "--inx.enabled=true"
      - "--inx.bindAddress=hornet:9029"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=hornet:9311"

##################################################################
#  Reverse Proxy and SSL                                         #
##################################################################

  traefik:
    container_name: traefik
    image: traefik:v2.10
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--metrics.prometheus=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "${HTTP_PORT:-80}:80/tcp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      #- "./data/letsencrypt:/letsencrypt"

##################################################################
#  Monitoring                                                    #
##################################################################

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    user: "65532"
    volumes:
      - ./data/sandboxdb/prometheus/:/prometheus
      - ./assets/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime:ro
    profiles:
      - monitoring

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    privileged: true
    command: 
      - --housekeeping_interval=30s    # kubernetes default args
      - --max_housekeeping_interval=35s
      - --event_storage_event_limit=default=0
      - --event_storage_age_limit=default=0
      - --store_container_labels=false
      - --global_housekeeping_interval=30s
      - --event_storage_event_limit=default=0
      - --event_storage_age_limit=default=0
      - --disable_metrics=accelerator,advtcp,cpu_topology,disk,hugetlb,memory_numa,percpu,referenced_memory,resctrl,sched,tcp,udp
      - --enable_load_reader=true
      - --docker_only=true          # only show stats for docker containers
      - --allow_dynamic_housekeeping=true
      - --storage_duration=1m0s
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    profiles:
      - monitoring

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "65532"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`localhost`) && (Path(`/grafana`) || PathPrefix(`/grafana/`))"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    environment:
      - GF_SERVER_ROOT_URL=/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_DOMAIN=localhost
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/node_dashboard.json
    volumes:
      - ./data/sandboxdb/grafana:/var/lib/grafana
      - ./assets/grafana/:/etc/grafana/provisioning/
    profiles:
      - monitoring

##################################################################
#  INX Extensions                                                #
#  disable them out by commenting out the services               #
##################################################################

  inx-indexer:
    container_name: inx-indexer
    image: iotaledger/inx-indexer:1.0
    stop_grace_period: 5m
    restart: unless-stopped
    depends_on:
      hornet:
        condition: service_healthy
    volumes:
      - ./data/sandboxdb/indexer:/app/database
    command:
      - "--inx.address=hornet:9029"
      - "--restAPI.bindAddress=inx-indexer:9091"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=inx-indexer:9312"

  inx-mqtt:
    container_name: inx-mqtt
    image: iotaledger/inx-mqtt:1.0
    stop_grace_period: 5m
    restart: unless-stopped
    depends_on:
      hornet:
        condition: service_healthy
    command:
      - "--inx.address=hornet:9029"
      - "--mqtt.websocket.bindAddress=inx-mqtt:1888"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=inx-mqtt:9312"

  inx-participation:
    container_name: inx-participation
    image: iotaledger/inx-participation:1.0
    stop_grace_period: 5m
    restart: unless-stopped
    depends_on:
      hornet:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    volumes:
      - ./data/sandboxdb/participation:/app/database
    command:
      - "--inx.address=hornet:9029"
      - "--restAPI.bindAddress=inx-participation:9892"

  inx-spammer:
    container_name: inx-spammer
    image: iotaledger/inx-spammer:1.0
    stop_grace_period: 5m
    restart: unless-stopped
    depends_on:
      hornet:
        condition: service_healthy
      inx-indexer:
        condition: service_started
    command:
      - "--inx.address=hornet:9029"
      - "--restAPI.bindAddress=inx-spammer:9092"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=inx-spammer:9312"

  inx-poi:
    container_name: inx-poi
    image: iotaledger/inx-poi:1.0
    stop_grace_period: 5m
    restart: unless-stopped
    depends_on:
      hornet:
        condition: service_healthy
    command:
      - "--inx.address=hornet:9029"
      - "--restAPI.bindAddress=inx-poi:9687"

  inx-dashboard:
    container_name: inx-dashboard
    image: iotaledger/inx-dashboard:1.0
    stop_grace_period: 5m
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hornet-dashboard.service=hornet-dashboard"
      - "traefik.http.routers.hornet-dashboard.rule=Host(`localhost`) && (Path(`/dashboard`) || PathPrefix(`/dashboard/`))"
      - "traefik.http.routers.hornet-dashboard.entrypoints=web"
      - "traefik.http.services.hornet-dashboard.loadbalancer.server.port=8081"
    volumes:
      - ./data/sandboxdb/dashboard:/app/database
    command:
      - "--inx.address=hornet:9029"
      - "--dashboard.bindAddress=inx-dashboard:8081"
      - "--dashboard.auth.identityFilePath=database/identity.key"
      - "--dashboard.auth.passwordHash=c4a3fcd2ebec3ac0d105411653284efa9c636e754b9fbbaf58b3adcb974f3655"
      - "--dashboard.auth.passwordSalt=11ed024b8f74191c8484579db15623435c994ae4c28d9ad1b2ad8c1807bf7469"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=inx-dashboard:9312"

##################################################################
#  Historic Data                                                 #
##################################################################

  inx-api-core-v0:
    container_name: inx-api-core-v0
    image: iotaledger/inx-api-core-v0:1.0
    stop_grace_period: 5m
    restart: unless-stopped
    depends_on:
      hornet:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    volumes:
      - ./data/sandboxdb/database_legacy:/app/database
    command:
      - "--inx.enabled=true"
      - "--inx.address=hornet:9029"
      - "--restAPI.bindAddress=inx-api-core-v0:9093"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=inx-api-core-v0:9312"
    profiles:
      - history-legacy

  inx-api-core-v1:
    container_name: inx-api-core-v1
    image: iotaledger/inx-api-core-v1:1.0
    stop_grace_period: 5m
    restart: unless-stopped
    depends_on:
      hornet:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    volumes:
      - ./data/sandboxdb/database_chrysalis:/app/database
    command:
      - "--inx.enabled=true"      
      - "--inx.address=hornet:9029"
      - "--restAPI.bindAddress=inx-api-core-v1:9094"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=inx-api-core-v1:9312"
    profiles:
      - history-chrysalis

##################################################################
#  WASP                                                          #
##################################################################

  wasp:
    container_name: wasp
    image: iotaledger/wasp:1.0-rc
    stop_grace_period: 5m
    restart: unless-stopped
    depends_on:
      hornet:
        condition: service_healthy
      inx-indexer:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wasp-api.service=wasp-api"
      - "traefik.http.routers.wasp-api.rule=Host(`localhost`) && (Path(`/wasp/api`) || PathPrefix(`/wasp/api/`))"
      - "traefik.http.routers.wasp-api.entrypoints=web"
      - "traefik.http.services.wasp-api.loadbalancer.server.port=9090"
      - "traefik.http.routers.wasp-api.middlewares=rewrite-wasp-api"
      - "traefik.http.middlewares.rewrite-wasp-api.stripprefix.prefixes=/wasp/api"
    volumes:
      - ./data/sandboxdb/wasp:/app/waspdb
    command:
      - "--logger.level=debug"
      - "--inx.address=hornet:9029"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=wasp:9312"
    profiles:
      - wasp

  wasp-dashboard:
    container_name: wasp-dashboard
    image: iotaledger/wasp-dashboard:latest
    stop_grace_period: 5m
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wasp-dashboard.service=wasp-dashboard"
      - "traefik.http.routers.wasp-dashboard.rule=Host(`localhost`) && (Path(`/wasp/dashboard`) || PathPrefix(`/wasp/dashboard/`))"
      - "traefik.http.routers.wasp-dashboard.entrypoints=web"
      - "traefik.http.services.wasp-dashboard.loadbalancer.server.port=80"
      - "traefik.http.routers.wasp-dashboard.middlewares=rewrite-wasp-dashboard"
      - "traefik.http.middlewares.rewrite-wasp-dashboard.stripprefix.prefixes=/wasp/dashboard"
    environment:
      - WASP_API_URL=http://localhost:${HTTP_PORT:-80}/wasp/api
      - L1_API_URL=http://localhost:${HTTP_PORT:-80}
    profiles:
      - wasp

##################################################################
#  Core                                                          #
#  This section contains bootstraping tools and a component      #
#  that should not be modified. It is recommended to leave       #
#  this section untouched to ensure proper functioning           #
#  of the application.                                           #
##################################################################

  inx-coordinator:
    container_name: inx-coordinator
    image: iotaledger/inx-coordinator:1.0
    depends_on:
      hornet:
        condition: service_healthy
    environment:
      - "COO_PRV_KEYS=651941eddb3e68cb1f6ef4ef5b04625dcf5c70de1fdc4b1c9eadb2c219c074e0ed3c3f1a319ff4e909cf2771d79fece0ac9bd9fd2ee49ea6c0885c9cb3b1248c,0e324c6ff069f31890d496e9004636fd73d8e8b5bea08ec58a4178ca85462325f6752f5f46a53364e2ee9c4d662d762a81efd51010282a75cd6bd03f28ef349c"
    volumes:
      - ./data/sandboxdb/state:/app/state
    command:
      - "--inx.address=hornet:9029"
      - "--coordinator.stateFilePath=state/coordinator.state"
      - "--coordinator.blockBackups.enabled=false"
      - "--profiling.enabled=true"
      - "--profiling.bindAddress=inx-coordinator:6060"

  hornet-1:
    container_name: hornet-1
    image: iotaledger/hornet:2.0
    networks:
      default:
        ipv4_address: 172.18.211.12
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    stop_grace_period: 5m
    cap_drop:
      - ALL
    volumes:
      - ./config_sandbox.json:/app/config.json:ro
      - ./data/sandboxdb/hornet-1:/app/data/sandboxdb
      - ./data/snapshots/hornet-1:/app/data/snapshots
    command:
      - "-c"
      - "config.json"
      - "--db.path=data/sandboxdb"
      - "--p2p.db.path=data/sandboxdb"
      - "--p2p.bindMultiAddresses=/ip4/0.0.0.0/tcp/15600,/ip6/::/tcp/15600"
      - "--snapshots.fullPath=data/snapshots/full_snapshot.bin"
      - "--snapshots.deltaPath=data/snapshots/delta_snapshot.bin"
      - "--inx.enabled=true"
      - "--inx.bindAddress=hornet-1:9029"
      - "--p2p.identityPrivateKey=a06b288ce7fc3b6f1e716f6f7d72050b53417aae4b305a68883550a3bb28597f254b082515a79391a7f13009b4133851a0c4d48e0e948809c3b46ff3e2500b4f"
      - "--p2p.peers=/ip4/172.18.211.11/tcp/15600/p2p/12D3KooWSagdVaCrS14GeJhM8CbQr41AW2PiYMgptTyAybCbQuEY"
      - "--p2p.peerAliases=hornet"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=hornet-1:9311"

  create-snapshots:
    container_name: create-snapshots
    image: iotaledger/hornet:2.0
    volumes:
      - ./protocol_parameters.json:/app/protocol_parameters.json:ro
      - ./data:/app/data
    command:
      - "tool"
      - "snap-gen"
      - "--protocolParametersPath=/app/protocol_parameters.json"
      - "--mintAddress=snd1qq2kvnu9pqzptkggrpqrvltvagccsh6aj2fkdhla7p3lrsy9dwhdzpu0epw"
      - "--genesisAddresses=snd1qpszqzadsym6wpppd6z037dvlejmjuke7s24hm95s9fg9vpua7vluuwu49a:1000000000000,snd1qqweu75ldpyann5jsthqsa6m0thx4tmqxncj6uqxf5q974pmqx30yfng7ya:1000000000000"
      - "--outputPath=data/snapshots/hornet/full_snapshot.bin"
    profiles:
      - snapshots

  bootstrap-network:
    container_name: bootstrap-network
    image: iotaledger/hornet:2.0
    environment:
      - "COO_PRV_KEYS=651941eddb3e68cb1f6ef4ef5b04625dcf5c70de1fdc4b1c9eadb2c219c074e0ed3c3f1a319ff4e909cf2771d79fece0ac9bd9fd2ee49ea6c0885c9cb3b1248c,0e324c6ff069f31890d496e9004636fd73d8e8b5bea08ec58a4178ca85462325f6752f5f46a53364e2ee9c4d662d762a81efd51010282a75cd6bd03f28ef349c"
    volumes:
      - ./config_sandbox.json:/app/config.json:ro
      - ./data/snapshots/hornet:/app/snapshots
      - ./data/sandboxdb/hornet:/app/sandboxdb
      - ./data/sandboxdb/state:/app/state
    command:
      - "tool"
      - "bootstrap-private-tangle"
      - "--configFile=config.json"
      - "--snapshotPath=snapshots/full_snapshot.bin"
      - "--databasePath=sandboxdb"
      - "--cooStatePath=state/coordinator.state"
    profiles:
      - bootstrap

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.18.211.0/24"
