name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Find and Replace VERSION
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "__VERSION__"
          replace: ${{ github.ref_name }}
          regex: false

      - name: Create iota_sandbox.tar.gz
        uses: ihiroky/archive-action@v1
        with:
          root_dir: sandbox
          file_path: iota_sandbox.tar.gz

      - name: Upload iota_sandbox.tar.gz file
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: iota_sandbox.tar.gz
          path: iota_sandbox.tar.gz
          repo-token: ${{ secrets.GITHUB_TOKEN }}