name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Find and Replace VERSION
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "__VERSION__"
          replace: ${{ github.ref_name }}
          regex: false

      - name: Create iota-sandbox_stardust.tar.gz
        uses: ihiroky/archive-action@v1
        with:
          root_dir: stardust
          file_path: iota-sandbox_stardust.tar.gz

      - name: Upload iota-sandbox_stardust.tar.gz file
        uses: Shopify/upload-to-release@v1.0.1
        with:
          name: iota-sandbox_stardust-${{ github.ref_name }}.tar.gz
          path: iota-sandbox_stardust.tar.gz
          repo-token: ${{ secrets.GITHUB_TOKEN }}
